### PR TITLE
Fixed Issue on all medication screen, now screen scrolls without hassle

### PR DESCRIPTION
**Pull request by Rhemi7**

### CODE REVIEW

**Comment by Rhemi7** [comment]
also removed a widget that wasn't used, the widget caused conflicts with importing

**Comment by cs-onah** [comment]
LoL.... the "Without Hassle" you added to the statement is very necessary

**Comment by iyiola-dev** [comment]
Without hassle🤣🤣🤣

**Comment by Rhemi7** [comment]
lmaoooo... true that

**Pull request merged**
